BillSystem/config/routes.rb
Rails.application.routes.draw do
  get 'static_page/Login'
  get 'clients/allclientWithBills'
  get 'bills/new'
  get '/', to: 'clients#index'

get 'clients/:id/bills', to: 'clients#show'


  resources :clients do
  	resources :bills, only: [:new, :create, :destroy]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

BillSystem/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BillSystem/app/models/bill.rb
class Bill < ApplicationRecord
  belongs_to :client

    validates :note, presence: true
	validates :Data, presence: true
	validates :totalHour, presence: true
	validates :totalEuro, presence: true
end

BillSystem/app/models/client.rb
class Client < ApplicationRecord

	has_many :bills, dependent: :destroy

	validates :name, presence: true
	validates :surename, presence: true
	validates :fiscalCode, presence: true
	validates :hourTariff, presence: true



end

BillSystem/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

BillSystem/app/controllers/bills_controller.rb
class BillsController < ApplicationController

  helper_method  :howMuchHaveIPay

  def new
  	@client = Client.find params[:client_id]
  	@bill = Bill.new
  end

  def create
    @client = Client.find params[:client_id] # we get the incident from the route
    # we build the status update using a method of the relation
    @bill = @client.bills.build(bill_params)
    respond_to do |format|
      if @bill.save
        format.html { redirect_to @client, notice: 'bill was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def destroy
  @bill = Bill.find params[:id]
 
  respond_to do |format|
    if @bill.destroy
      format.html { redirect_to @bill.client,
                    notice: 'Bill was successfully deleted.'}
    else
      format.html { redirect_to @bill.client,
                    alert: 'Could not delete this bill'}
    end
  end
end

def howMuchHaveIPay
	tarif = @bill.client.hourTariff
	total = @bill.totalHour * tarif
	return total
end
 
  private
 
  def bill_params
    params.require(:bill).permit(:note, :Data, :totalEuro, :totalHour)
  end

end

BillSystem/app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]
  helper_method :sayHello, :total

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  def allclientWithBills
    @clients = Client.all
  end

  def sayHello
    "hello"
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  def total
    tot = 0
    tarif = @client.hourTariff
    @client.bills.each do |i|
      tot = tot + (i.totalHour * tarif)
    end
    return tot
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :surename, :fiscalCode, :hourTariff)
    end
end

BillSystem/app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
	
end

BillSystem/app/helpers/application_helper.rb
module ApplicationHelper
end

BillSystem/app/helpers/bills_helper.rb
module BillsHelper
end

BillSystem/app/helpers/clients_helper.rb
module ClientsHelper
end

BillSystem/app/helpers/static_page_helper.rb
module StaticPageHelper
end

BillSystem/app/views/bills/_form.html.erb
<%= form_with(model: bill, local: true) do |form| %>

  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name, id: :bill_note, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

BillSystem/app/views/bills/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

BillSystem/app/views/bills/new.html.erb
<h1>Add fattures to client: <%#@clients%></h1>
<%= form_for([@client, @bill]) do |form| %>
 


<div class="form-group">
    <%= form.label :Note%>
    <%= form.text_field :note, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :data %>
    <%= form.date_field :Data, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :totalEuro %>
    <%= form.number_field :totalEuro, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :totalHour %>
    <%= form.number_field :totalHour, class: "form-control" %>
  </div>
 
  <div class="actions">
    <%= form.submit class: "btn btn-primary btn-lg active"%>
  </div>
<%end%>

BillSystem/app/views/clients/_form.html.erb
<%= form_with(model: client, local: true) do |form| %>
  <% if client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name%>
    <%= form.text_field :name, id: :client_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :surename %>
    <%= form.text_field :surename, id: :client_surename, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :fiscalCode %>
    <%= form.text_field :fiscalCode, id: :client_fiscalCode, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :hourTariff %>
    <%= form.number_field :hourTariff, id: :client_hourTariff, class: "form-control" %>
  </div>

  <div class="action">
    <%= form.submit class: "btn btn-primary btn-lg active" %>
    <%= link_to 'Back', clients_path, class: "btn btn-primary btn-lg active"%>
  </div>
<% end %>

BillSystem/app/views/clients/allclientWithBills.html.erb
    <h1>Clients</h1>
    <table class="table table-striped table-inverse">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Surname</th>
          <th>Fiscalcode</th>
          <th>Hourtariff</th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <th scope="row"><%@client_id%></th>
            <th><%= client.name %></th>
            <th><%= client.surename %></th>
            <th><%= client.fiscalCode %></th>
            <th><%= client.hourTariff %></th>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="btn-group btn-group-justified" role="group" width="100%">
      <%= link_to 'New client', new_client_path, class: "btn btn-primary btn-lg active"%>
    </div>

<div class="btn-group btn-group-justified" role="group">

</div>

BillSystem/app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form', client: @client %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

BillSystem/app/views/clients/index.html.erb
    <h1>Clients</h1>
    <table class="table table-striped table-inverse">
      <thead class="thead-dark">
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Surname</th>
          <th>Fiscalcode</th>
          <th>Hourtariff</th>
          <th> </th>
          <th> </th>
          <th> </th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr>
            <th scope="row"><%@client_id%></th>
            <th><%= client.name %></th>
            <th><%= client.surename %></th>
            <th><%= client.fiscalCode %></th>
            <th><%= client.hourTariff %></th>
            <th><%= link_to 'Show bills relative this client', client %></th>
            <th><%= link_to 'Edit', edit_client_path(client) %></th>
            <th><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></th>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>
    <div class="btn-group btn-group-justified" role="group" width="100%">
      <%= link_to 'New client', new_client_path, class: "btn btn-primary btn-lg active"%>
    </div>

<div class="btn-group btn-group-justified" role="group">

</div>

BillSystem/app/views/clients/new.html.erb
<h1>New Client</h1>

<%= render 'form', client: @client %>

BillSystem/app/views/clients/show.html.erb
<table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Surname</th>
          <th>Fiscalcode</th>
          <th>Hourtariff</th>
        </tr>
      </thead>

      <tbody>
          <tr>
            <th><%= @client.name %></th>
            <th><%= @client.surename %></th>
            <th><%= @client.fiscalCode %></th>
            <th><%= @client.hourTariff %></th>
          </tr>
      </tbody>
  </table>


	

<%if @client.bills.any?%>
<table class="table">
	      <thead class="thead-dark">
	        <tr>
	          <th>Note</th>
	          <th>Date</th>
	          <th>TotalHour</th>
	          <th>totalEuro</th>
	          <th>Earn</th>
	          <th></th>
	        </tr>
	      </thead>
	      <tbody>
	          <tr>
	          	<%@client.bills.each do |i|%>
	            <th><%= i.note %></th>
	            <th><%= i.Data%></th>
	            <th><%= i.totalHour %></th>
	            <th><%= i.totalEuro %></th>
	            <th><%=i.totalHour * @client.hourTariff%></th>
	            <th>[<%= link_to  'Delete',
                  client_bill_path(@client, i),
                  method: :delete,
                  data: { confirm: 'Are you sure?'}
    %>]</th>
	          </tr>
	          <% end -%>

	          <tr style="background-color: #a76a70">
	          	<th >Total :</th>
	          	<th><%=total%></th>
	          </tr>
	      </tbody>
	  </table>
<%else%>
	<h1>No bill in this moment</h1>
<%end%>

<br>
<%= link_to 'Edit', edit_client_path(@client), class: "btn btn-primary btn-lg active"%>
<%= link_to 'Back', clients_path, class: "btn btn-primary btn-lg active" %>
<%= link_to 'add Bills', new_client_bill_path(@client), class: "btn btn-primary btn-lg active" %>

BillSystem/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BillSystem</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>

<%= render 'pages/navbar'%>
	<div class="container">
  		<!--<div class="row">-->

			<%= yield %>
		<!--</div>-->
	</div>

  </body>
</html>

BillSystem/app/views/pages/_navbar.html.erb
<div class="jumbotron">
      <div class="container">
        <h1 class="display-3" style="text-align: center;">You are in BillingSysytem</h1>
      </div>
    </div>

BillSystem/app/views/static_page/Login.html.erb
<!DOCTYPE html>
<html>
<style>
form {
    border: 3px solid #f1f1f1;
}

input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

button {
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
<body>

<h2>Login Form</h2>

<form action="/action_page.php">
  <div class="imgcontainer">
    <img src="img_avatar2.png" alt="Avatar" class="avatar">
  </div>

  <div class="container">
    <label><b>Username</b></label>
    <input type="text" placeholder="Enter Username" name="uname" required>

    <label><b>Password</b></label>
    <input type="password" placeholder="Enter Password" name="psw" required>
        
    <button type="submit">Login</button>
    <input type="checkbox" checked="checked"> Remember me
  </div>

  <div class="container" style="background-color:#f1f1f1">
    <button type="button" class="cancelbtn">Cancel</button>
    <span class="psw">Forgot <a href="#">password?</a></span>
  </div>
</form>

</body>
</html>